DROP DATABASE IF EXISTS metro_warehouse;

create schema metro_warehouse;
use metro_warehouse;

drop table if exists products;
drop table if exists TIME_Dimension;
drop table if exists Customer;
drop table if exists Store;
drop table if exists Supplier;
drop table if exists Fact_Table;


CREATE TABLE `PRODUCTS` (
`PRODUCT_ID` VARCHAR(6) NOT NULL, 
`PRODUCT_NAME` VARCHAR(30) NOT NULL, 
`PRICE` DECIMAL(5,2) DEFAULT (0.0) NOT NULL,
CONSTRAINT PRODUCTS_PK PRIMARY KEY (PRODUCT_ID));

CREATE TABLE `SUPPLIER` (
`SUPPLIER_ID` VARCHAR(5) NOT NULL, 
`SUPPLIER_NAME` VARCHAR(30) NOT NULL, 
CONSTRAINT SUPPLIER_PK PRIMARY KEY (SUPPLIER_ID));

CREATE TABLE `STORE` (
`STORE_ID` VARCHAR(4) NOT NULL, 
`STORE_NAME` VARCHAR(20) NOT NULL, 
CONSTRAINT STORE_PK PRIMARY KEY (STORE_ID));

CREATE TABLE `CUSTOMER` (
`CUSTOMER_ID` VARCHAR(4) NOT NULL, 
`CUSTOMER_NAME` VARCHAR(30) NOT NULL, 
CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID));

CREATE TABLE `TIME_Dimension` (
`TIME_ID` INT NOT NULL AUTO_INCREMENT,
`T_DATE` DATE NOT NULL,
CONSTRAINT TIME_PK PRIMARY KEY (TIME_ID));

CREATE TABLE `FACT_TABLE` (
`PRODUCT_ID` VARCHAR(6) NOT NULL, 
`CUSTOMER_ID` VARCHAR(4) NOT NULL, 
`STORE_ID` VARCHAR(4) NOT NULL,
`TRANSACTION_ID` INT NOT NULL, 
`SUPPLIER_ID` VARCHAR(5) NOT NULL,
`QUANTITY` SMALLINT NOT NULL,
`TOTAL_SALES` INT NOT NULL,
`T_DATE` DATE NOT NULL,

CONSTRAINT SALE_FK PRIMARY KEY(TRANSACTION_ID,PRODUCT_ID),
CONSTRAINT PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
CONSTRAINT STORE_ID_FK FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID),
CONSTRAINT SUPPLIER_ID_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID));

commit;
show tables;
